// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEsbbsfw1tWsgrhHvCzSe-xfidCEsL4s',
    appId: '1:1046290022275:web:15931ed427fe46184400b6',
    messagingSenderId: '1046290022275',
    projectId: 'stylecast-310',
    authDomain: 'stylecast-310.firebaseapp.com',
    storageBucket: 'stylecast-310.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwl7V8Bhq-c5mSsGTxb8f-MHL-t_zV64',
    appId: '1:1046290022275:android:3a6142542913b91d4400b6',
    messagingSenderId: '1046290022275',
    projectId: 'stylecast-310',
    storageBucket: 'stylecast-310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAWWNPj-ib68bfYkytKrs4MzE6sQVBH90',
    appId: '1:1046290022275:ios:2dc42dc2727ba57b4400b6',
    messagingSenderId: '1046290022275',
    projectId: 'stylecast-310',
    storageBucket: 'stylecast-310.firebasestorage.app',
    iosBundleId: 'com.cs310.stylecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAWWNPj-ib68bfYkytKrs4MzE6sQVBH90',
    appId: '1:1046290022275:ios:2b64314708d3982e4400b6',
    messagingSenderId: '1046290022275',
    projectId: 'stylecast-310',
    storageBucket: 'stylecast-310.firebasestorage.app',
    iosBundleId: 'com.example.quack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvEsbbsfw1tWsgrhHvCzSe-xfidCEsL4s',
    appId: '1:1046290022275:web:07dbbf32c307c7c04400b6',
    messagingSenderId: '1046290022275',
    projectId: 'stylecast-310',
    authDomain: 'stylecast-310.firebaseapp.com',
    storageBucket: 'stylecast-310.firebasestorage.app',
  );
}
